name: Build Windows Driver

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [ARM64]  # Specify ARM64 as the target platform
    runs-on: windows-2022
    env:
      Solution_Path: driver\kmdf\fts5cu56a.vcxproj  # Path to your driver project file (.vcxproj)
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Archive all build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: driver-build
          path: |
            driver\kmdf\ARM64\${{ matrix.configuration }}\*  # Adjust the path to match where your build outputs are stored
